### PR TITLE
scripts: add export-data.js; closes #1

### LINKED ISSUE #1: Feature request: Download all your data
A command that downloads the entire data-set for somebody and stores it in some structured way. 
FYI, my last attempt at it resulted in: https://github.com/dciobanu/ciscospark-export

### PR DESCRIPTION
**Pull request by hagemt**
Usage is interactive. @dciobanu, you probably have opinions on this.

### CODE REVIEW

**Comment by dciobanu** [comment]
Notes:
Doesn't resolve ~ correctly
IMHO there should be a export format option: line-by-line JSON blob, formatted JSON array or CSV

**Comment by dciobanu** [comment]
Exporting content & avatars would be useful too

**Comment by dciobanu** [comment]
Note: Make sure non-interactive use works

**Comment by hagemt** [comment]
I'm calling this script beta quality. TODOs left before merge:

- [x]: support tilde, and default to pretty JSON as export format
- [ ]: figure out why avatar (download blob) export doesn't work
- [ ]: figure out why messages files are sometimes empty?

Will do the content export (maybe) and format flags in follow-on PRs.

**Pull request merged**
